import Head from 'next/head'
import { PrismaClient } from '@prisma/client'
import { useState, useEffect } from 'react'
import { useCookies } from 'react-cookie'

export default function Home({data}) {

  const [currentUser, setCurrentUser] = useState(null)
  const [cookies] = useCookies(['user'])

  useEffect(() => {
    setCurrentUser(cookies.user)
  }, [cookies.user])
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Festiv-app</h1>
      <h2>Bonjour {currentUser?.firstName}</h2>
      <p>Nom des festivaliers</p>
      {data.map((elt, i) =>(
        <div key={i}>
          <p>{elt.firstName}</p>
        </div>
      ))}
    </div>
  )
}

export async function getServerSideProps(){
  const prisma = new PrismaClient()
  const data = await prisma.user.findMany()


  console.log(data)
  return{
    props:{
      data
    }
  }
}
