import Head from 'next/head'
import { PrismaClient } from '@prisma/client'

export default function Home({data}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Festiv-app</h1>
      <p>Nom des festivaliers</p>
      {data.map((elt, i) =>(
        <div key={i}>
          <p>{elt.firstName}</p>
        </div>
      ))}
    </div>
  )
}

export async function getServerSideProps(){
  const prisma = new PrismaClient()
  const data = await prisma.user.findMany()


  console.log(data)
  return{
    props:{
      data
    }
  }
}
